### ISSUE TITLE
Link to Wikidata is missing on lexeme

### ISSUE THREAD

**Issue by dpriskorn** [fnielsen/synia#2]
![Screenshot_20230921-171618_Firefox.png](https://github.com/fnielsen/synia/assets/68460690/0dc8b1dd-1c5d-4b26-a267-4af7d1086a68)

https://synia.toolforge.org/#lexeme/L184796

**Comment by fnielsen** [comment]
It is actually not a Synia issue. You can change the page your self on Wikidata. It is defined here: https://www.wikidata.org/wiki/Wikidata:Synia:lexeme

**Comment by fnielsen** [comment]
I have opened this again because we can add it

**Comment by fnielsen** [comment]
There is now a link: https://synia.toolforge.org/#lexeme/L184796
