### ISSUE TITLE
Senses are missing on lexeme

### ISSUE THREAD

**Issue by dpriskorn** [fnielsen/synia#3]
![Screenshot_20230921-172052_Firefox.png](https://github.com/fnielsen/synia/assets/68460690/bd22460d-b7b4-468e-b2ab-66121a0e3827)

https://synia.toolforge.org/#lexeme/L184795

![Screenshot_20230921-172148_Firefox.png](https://github.com/fnielsen/synia/assets/68460690/b2d8c749-a92a-4a9e-b887-cafb8a9b518e)

**Comment by fnielsen** [comment]
It is actually not a Synia issue. You can change the page your self on Wikidata. It is defined here: https://www.wikidata.org/wiki/Wikidata:Synia:lexeme

**Comment by fnielsen** [comment]
https://synia.toolforge.org/#lexeme/L184795
